job_application.form:
  path: '/job-application/form'
  defaults:
    _title: 'Job Application Form'
    _form: 'Drupal\job_application\Form\JobApplicationForm'
  requirements:
    _permission: 'access content'
