<?php

  use Drupal\job_application\Controller\SendEmailsController;

  /**
   * @file
   * Primary module hooks for Job application module.
   */

  /**
   * Implements hook_schema().
   */
  function job_application_schema()
  {
    $schema = [];

    $schema['job_applications'] = [
      'description' => 'Data from application job form',
      'fields' => [
        'jaid' => [
          'type' => 'serial',
          'unsigned' => TRUE,
          'not null' => TRUE,
          'description' => 'Job Applicant ID',
        ],
        'name' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
          'description' => 'Applicant name',
        ],
        'mail' => [
          'type' => 'varchar',
          'length' => 255,
          'not null' => TRUE,
          'description' => 'Applicant email',
        ],
        'type' => [
          'type' => 'varchar',
          'length' => 16,
          'not null' => TRUE,
          'description' => 'Backend or Frontend',
        ],
        'technology' => [
          'type' => 'varchar',
          'length' => 16,
          'not null' => TRUE,
          'description' => 'Backend or Frontend technologies',
        ],
        'message' => [
          'type' => 'text',
          'description' => 'Message for employer',
        ],
        'created' => [
          'type' => 'int',
          'not null' => TRUE,
          'description' => 'Timestamp when the record was created.',
        ],

      ],
      'primary key' => ['jaid'],
    ];

    return $schema;
  }

  function job_application_mail($key, &$message, $params) {

    switch ($key) {
      case 'job_application_submission':
        $message['subject'] = isset($params['subject']) ? $params['subject'] : '';
        $message['body'][] = isset($params['body']) ? $params['body'] : '';
        break;

      case 'job_application_weekly_news_for_applicants':
        $config = \Drupal::config('job_application.settings');
        $subject = $config->get('email_title');
        $body = $config->get('email_body');

        $message['subject'] = $subject;
        $message['body'][] = $body;
        break;
    }
  }

  /**
   * Implements hook_cron().
   */

  function job_application_cron()
  {

    $current_day = date('l');
    $current_hour = date('H');

    if ($current_day === 'Monday' && $current_hour === '08') {

      $oneWeekAgo = strtotime('-7 days');
      $query = \Drupal::database()->select('job_applications', 'ja');
      $query->fields('ja', ['mail', 'created']);
      $query->condition('ja.created', $oneWeekAgo, '>=');
      $email_addresses = $query->execute()->fetchAll();

      $queue = \Drupal::queue('job_application_sending_weekly_emails');

      foreach ($email_addresses as $email) {
        $data = ['to' => $email];
        $queue->createItem($data);
      }
    }
  }











