job_application.form:
  path: '/job-application/form'
  defaults:
    _title: 'Job Application Form'
    _form: 'Drupal\job_application\Form\JobApplicationForm'
  requirements:
    _permission: 'access content'

job_application.admin_table:
  path: '/admin/job-applications/list'
  defaults:
    _controller: '\Drupal\job_application\Controller\JobApplicationTableController::content'
    _title: 'Job Applications'
  requirements:
    _permission: 'administer site configuration'

job_application.email_send_settings:
  path: '/admin/job-applications/email-form'
  defaults:
    _title: 'Email send settings'
    _form: 'Drupal\job_application\Form\EmailSendSettingsForm'
  requirements:
    _permission: 'administer job application'
