name: 'Job application'
type: module
description: 'Webform for job applications that stores data in a SQL database and sends it to the designated email on our website. All the collected information is accessible on an HTML page in the backend. Additionally, automated weekly emails will be dispatched to all job applicants.'
package: Custom
core_version_requirement: ^10
