# Schema for the configuration files of the Job application module.
job_application.settings:
  type: config_object
  label: 'Job application settings'
  mapping:
    example:
      type: string
      label: 'Example'
